server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # SPA : toute route inconnue retombe sur index.html (routing géré côté Angular)
    location / {
        try_files $uri $uri/ /index.html;
    }
}
