from typing import List, Optional

from sqlalchemy.orm import Session

from app.db.models import Client

def format_client_number(client_id: int) -> str:
    """Turns the database's auto-increment id into a stable, bank-style
    reference (e.g. CLI-000042) — generated by the system, never typed
    by the analyst, exactly how a real client/account number works.
    """
    return f"CLI-{client_id:06d}"
class ClientRepository:
     

    def __init__(self, db: Session):
        self._db = db

    def get_by_id(self, client_id: int) -> Optional[Client]:
        return self._db.get(Client, client_id)

    def list_all(self) -> List[Client]:
        return list(self._db.query(Client).order_by(Client.created_at.desc()).all())

    def create(self, label: str) -> Client:
        client = Client(label=label)
        self._db.add(client)
        self._db.commit()
        self._db.refresh(client)
        return client

    def get_or_create(self, client_id: Optional[int], new_client_label: Optional[str]) -> Client:
        
        if client_id is not None:
            client = self.get_by_id(client_id)
            if client is None:
                raise ValueError(f"Client {client_id} not found")
            return client
        return self.create(new_client_label)